// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface FeedValidation$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "FeedValidation";
  readonly sourceName: "contracts/libraries/FeedValidation.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220bab7d299848832f8010ef9011ed70e8558cd4fc6a96df79b2cf3959d37eacdf364736f6c634300081e0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220bab7d299848832f8010ef9011ed70e8558cd4fc6a96df79b2cf3959d37eacdf364736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/FeedValidation.sol";
  readonly buildInfoId: "solc-0_8_30-53912771f68c89d1d8ffad4452b66ac349641e0c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["FeedValidation"]: FeedValidation$Type;
    ["contracts/libraries/FeedValidation.sol:FeedValidation"]: FeedValidation$Type;
  }
}