// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface RedeemLogic$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "RedeemLogic";
  readonly sourceName: "contracts/libraries/RedeemLogic.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212209ac3c34bf9a46831e8ff5943cc7bdf76a2e828ea672c0ffc18e2e83c82f2ddcd64736f6c634300081e0033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212209ac3c34bf9a46831e8ff5943cc7bdf76a2e828ea672c0ffc18e2e83c82f2ddcd64736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/RedeemLogic.sol";
  readonly buildInfoId: "solc-0_8_30-53912771f68c89d1d8ffad4452b66ac349641e0c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["RedeemLogic"]: RedeemLogic$Type;
    ["contracts/libraries/RedeemLogic.sol:RedeemLogic"]: RedeemLogic$Type;
  }
}