// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface CollateralMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "CollateralMath";
  readonly sourceName: "contracts/libraries/CollateralMath.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220d5e8897f96e0636cba3b0cad7ed303eb6ce748b353c8991fc3ac5ace67fc000c64736f6c634300081e0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220d5e8897f96e0636cba3b0cad7ed303eb6ce748b353c8991fc3ac5ace67fc000c64736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/CollateralMath.sol";
  readonly buildInfoId: "solc-0_8_30-53912771f68c89d1d8ffad4452b66ac349641e0c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["CollateralMath"]: CollateralMath$Type;
    ["contracts/libraries/CollateralMath.sol:CollateralMath"]: CollateralMath$Type;
  }
}