// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IUSDMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IUSDMath";
  readonly sourceName: "contracts/libraries/IUSDMath.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220a4fa0352c876cc0c63503148937f3168893c6bd847e503e5525492a3686c03fb64736f6c634300081e0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220a4fa0352c876cc0c63503148937f3168893c6bd847e503e5525492a3686c03fb64736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/IUSDMath.sol";
  readonly buildInfoId: "solc-0_8_30-53912771f68c89d1d8ffad4452b66ac349641e0c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IUSDMath"]: IUSDMath$Type;
    ["contracts/libraries/IUSDMath.sol:IUSDMath"]: IUSDMath$Type;
  }
}