// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IUniswapV2TWAPOracle$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IUniswapV2TWAPOracle";
  readonly sourceName: "contracts/interfaces/IUniswapV2TWAPOracle.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"pair","type":"address"},{"internalType":"uint8","name":"token0Decimals","type":"uint8"},{"internalType":"uint8","name":"token1Decimals","type":"uint8"}],"name":"getTWAPPrice","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"pair","type":"address"}],"name":"isTWAPReady","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"pair","type":"address"}],"name":"update","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IUniswapV2TWAPOracle.sol";
  readonly buildInfoId: "solc-0_8_30-53912771f68c89d1d8ffad4452b66ac349641e0c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IUniswapV2TWAPOracle"]: IUniswapV2TWAPOracle$Type;
    ["contracts/interfaces/IUniswapV2TWAPOracle.sol:IUniswapV2TWAPOracle"]: IUniswapV2TWAPOracle$Type;
  }
}