// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Constants$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Constants";
  readonly sourceName: "contracts/libraries/Constants.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220a5d97784e7839df7a23d5960e39bbcda3eddd11ac5f030d63170a0b576aab41c64736f6c634300081e0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220a5d97784e7839df7a23d5960e39bbcda3eddd11ac5f030d63170a0b576aab41c64736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/Constants.sol";
  readonly buildInfoId: "solc-0_8_30-53912771f68c89d1d8ffad4452b66ac349641e0c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Constants"]: Constants$Type;
    ["contracts/libraries/Constants.sol:Constants"]: Constants$Type;
  }
}