// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface RewardMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "RewardMath";
  readonly sourceName: "contracts/libraries/RewardMath.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220a9be3576ddbe8ce6b646a6a063fb1f11a3a03b97e84f6b39e0e797d614b8c03464736f6c634300081e0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220a9be3576ddbe8ce6b646a6a063fb1f11a3a03b97e84f6b39e0e797d614b8c03464736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/RewardMath.sol";
  readonly buildInfoId: "solc-0_8_30-53912771f68c89d1d8ffad4452b66ac349641e0c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["RewardMath"]: RewardMath$Type;
    ["contracts/libraries/RewardMath.sol:RewardMath"]: RewardMath$Type;
  }
}