// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IIdealUSDManager$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IIdealUSDManager";
  readonly sourceName: "contracts/interfaces/IIdealUSDManager.sol";
  readonly abi: [{"inputs":[],"name":"getCurrentIUSD","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"lastUpdateTime","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IIdealUSDManager.sol";
  readonly buildInfoId: "solc-0_8_30-53912771f68c89d1d8ffad4452b66ac349641e0c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IIdealUSDManager"]: IIdealUSDManager$Type;
    ["contracts/interfaces/IIdealUSDManager.sol:IIdealUSDManager"]: IIdealUSDManager$Type;
  }
}