// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface PriceBlend$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "PriceBlend";
  readonly sourceName: "contracts/libraries/PriceBlend.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea264697066735822122096e7745ef07c4e1da74debdd89b75cb53ef8bbb759162d0afc9061a7a2f9fb6e64736f6c634300081e0033";
  readonly deployedBytecode: "0x5f80fdfea264697066735822122096e7745ef07c4e1da74debdd89b75cb53ef8bbb759162d0afc9061a7a2f9fb6e64736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/PriceBlend.sol";
  readonly buildInfoId: "solc-0_8_30-53912771f68c89d1d8ffad4452b66ac349641e0c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["PriceBlend"]: PriceBlend$Type;
    ["contracts/libraries/PriceBlend.sol:PriceBlend"]: PriceBlend$Type;
  }
}