// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface InterestMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "InterestMath";
  readonly sourceName: "contracts/libraries/InterestMath.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220fa622202a4124d89f91b9d302d46ee070751e0fac97431961d2640f4f3dcdd4f64736f6c634300081e0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220fa622202a4124d89f91b9d302d46ee070751e0fac97431961d2640f4f3dcdd4f64736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/InterestMath.sol";
  readonly buildInfoId: "solc-0_8_30-53912771f68c89d1d8ffad4452b66ac349641e0c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["InterestMath"]: InterestMath$Type;
    ["contracts/libraries/InterestMath.sol:InterestMath"]: InterestMath$Type;
  }
}