// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockRedstone$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockRedstone";
  readonly sourceName: "contracts/local/MockRedstone.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"dataFeedId","type":"bytes32"}],"name":"getValueForDataFeedId","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"dataFeedId","type":"bytes32"},{"internalType":"uint256","name":"price","type":"uint256"}],"name":"setValue","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"name":"values","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x6080806040523460155761011d908161001a8239f35b5f80fdfe608060405260043610156010575f80fd5b5f3560e01c80636cfd19ea1460c35780637a1202c81460615763ccc2195f146036575f80fd5b34605d576020366003190112605d576004355f525f602052602060405f2054604051908152f35b5f80fd5b34605d576020366003190112605d576004355f525f60205260405f20548015608e57602090604051908152f35b60405162461bcd60e51b815260206004820152600d60248201526c15985b1d59481b9bdd081cd95d609a1b6044820152606490fd5b34605d576040366003190112605d576004355f525f60205260243560405f20555f80f3fea26469706673582212206aae258fd154fc93f59b5bea4213c835623c8bb06c22c1929f357802a463c69d64736f6c634300081e0033";
  readonly deployedBytecode: "0x608060405260043610156010575f80fd5b5f3560e01c80636cfd19ea1460c35780637a1202c81460615763ccc2195f146036575f80fd5b34605d576020366003190112605d576004355f525f602052602060405f2054604051908152f35b5f80fd5b34605d576020366003190112605d576004355f525f60205260405f20548015608e57602090604051908152f35b60405162461bcd60e51b815260206004820152600d60248201526c15985b1d59481b9bdd081cd95d609a1b6044820152606490fd5b34605d576040366003190112605d576004355f525f60205260243560405f20555f80f3fea26469706673582212206aae258fd154fc93f59b5bea4213c835623c8bb06c22c1929f357802a463c69d64736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/local/MockRedstone.sol";
  readonly buildInfoId: "solc-0_8_30-53912771f68c89d1d8ffad4452b66ac349641e0c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockRedstone"]: MockRedstone$Type;
    ["contracts/local/MockRedstone.sol:MockRedstone"]: MockRedstone$Type;
  }
}