// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface OracleMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "OracleMath";
  readonly sourceName: "contracts/libraries/OracleMath.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220232a562c1bde0be52789f2ef04b054e0e391e28a96cc650476f8bd742476ca3e64736f6c634300081e0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220232a562c1bde0be52789f2ef04b054e0e391e28a96cc650476f8bd742476ca3e64736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/OracleMath.sol";
  readonly buildInfoId: "solc-0_8_30-53912771f68c89d1d8ffad4452b66ac349641e0c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["OracleMath"]: OracleMath$Type;
    ["contracts/libraries/OracleMath.sol:OracleMath"]: OracleMath$Type;
  }
}