// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MintLogic$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MintLogic";
  readonly sourceName: "contracts/libraries/MintLogic.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220c1d49e1d7876b74aa9a0a32f05638fe20a9cb1bd5f9b8920cfa06a082eec36a964736f6c634300081e0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220c1d49e1d7876b74aa9a0a32f05638fe20a9cb1bd5f9b8920cfa06a082eec36a964736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/MintLogic.sol";
  readonly buildInfoId: "solc-0_8_30-53912771f68c89d1d8ffad4452b66ac349641e0c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MintLogic"]: MintLogic$Type;
    ["contracts/libraries/MintLogic.sol:MintLogic"]: MintLogic$Type;
  }
}